---
kind: pipeline
type: docker
name: Maven_Build

steps:

- name: 1_PreCheck_scripts
  image: alpine
  commands:
  - echo Checking if I am anonymous or any operations
  - cat /etc/*-release
  - whoami

- name: 2_Build_The_Code
  image: alpine
  commands:
  - echo A Build Simulation
  - echo DONE

- name: 3_Maven_Settings_File
  image: webdevops/go-replace
  environment:
    PROXY_USERNAME:
      from_secret: PROXY_USERNAME
    PROXY_PASSWORD:
      from_secret: PROXY_PASSWORD
  commands:
  - go-replace -s "PROXY_USERNAME" -r $PROXY_USERNAME src/settings.xml
  - go-replace -s "PROXY_PASSWORD" -r $PROXY_PASSWORD src/settings.xml

- name: 4_Wrap-up
  image: alpine
  commands:
  - ls -ls
  - cat src/settings.xml
