---
kind: pipeline
type: docker
name: Maven_Build

steps:

- name: 1_PreCheck_scripts
  image: alpine
  commands:
  - echo Checking if I am anonymous or any operations
  - cat /etc/*-release
  - whoami

- name: 2_Build_The_Code
  image: alpine
  commands:
  - echo A Build Simulation
  - echo DONE

- name: 3_Maven_Settings_File
  image: webdevops/go-replace
  commands:
  - go-replace -s "PROXY_USERNAME" -r ecointet src/settings.xml
  - echo DONE

- name: 4_Wrap-up
  image: alpine
  commands:
  - ls -ls
  - cat settings.xml
